// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqJg0rQgR-ANy5xn9ff7j1LJP3pWSiGY',
    appId: '1:888835143892:web:c75b99825a73023fa0e341',
    messagingSenderId: '888835143892',
    projectId: 'hsa-app-534ea',
    authDomain: 'hsa-app-534ea.firebaseapp.com',
    storageBucket: 'hsa-app-534ea.appspot.com',
    measurementId: 'G-8Z35431T5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbVfT15jy-Lh4X10XiLaCcMP3vVi1f3p8',
    appId: '1:888835143892:android:6b0dd2140ee2a613a0e341',
    messagingSenderId: '888835143892',
    projectId: 'hsa-app-534ea',
    storageBucket: 'hsa-app-534ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPXDx525WrguAs0gwyM4bC5uLICvT2iCw',
    appId: '1:888835143892:ios:ec494a505d5bd7d4a0e341',
    messagingSenderId: '888835143892',
    projectId: 'hsa-app-534ea',
    storageBucket: 'hsa-app-534ea.appspot.com',
    iosClientId: '888835143892-s0rr6uiqa30tqdh7rr82oa632vlris7i.apps.googleusercontent.com',
    iosBundleId: 'com.hsa.hsaApp',
  );
}
